version: '2'

services:

  wordpress:
    image: tlezotte/wordpress
    ports:
      - 8443:443
    environment:
      WORDPRESS_DB_PASSWORD: Q2n0exmL
    volumes:
      - ./html:/var/www/html
      - ./html_log:/var/log/apache2/

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Q2n0exmL
    volumes: 
      - ./database:/var/lib/mysql
      - ./database_log:/var/log/mysql
